
import os
home = os.getcwd()


DATA_DIR = "./data/"
IMGS_DIR = DATA_DIR+"imgs/"
WYRS_DIR = DATA_DIR+"wyrs/"
VID_DIR = DATA_DIR+"vids/"
TEMP_DIR = DATA_DIR+"temp/"
TRASH_DIR = DATA_DIR+"trash/"


STATIC_DIR = "./static/"
SOUNDS_DIR = STATIC_DIR + "sounds/"


WYR_INDICATOR = "_A_WYR"
WYR_SOUND_INDICATOR = "_A_SOUNDWYR"
WYR_CONCLUSION_INDICATOR = "_B_CONCLUSIONWYR"
WYR_CONCLUSION_SOUND_INDICATOR = "_B_SOUNDCONCLUSIONWYR"
CTA_INDICATOR = "_A_CTA"
CTA_SOUND_INDICATOR = "_A_SOUNDCTA"

